sonar.projectKey=hblab-e-commerce
sonar.organization=hblab-haind

sonar.sources=packages/Webkul/Wishlist
sonar.exclusions=**/vendor/**,**/node_modules/**,**/tests/**,**/database/migrations/**

sonar.language=php
sonar.sourceEncoding=UTF-8
